### ISSUE TITLE
Erweitern auf Plugins :)?

### ISSUE THREAD

**Issue by lhwparis** [simkli/SimklThemeSettingExport#2]
Hi, erst mal vielen Dank für das Plugin, es ist echt super nützlich, vorallem die CLI Variante.
Wäre es denkbar, dass du es auch auf Plugins erweiterst? Da wäre ein Export/Import aller Plugin Settings über die CLI auch extrem nützlich.

**Comment by simkli** [comment]
There are two commands provided by Shopware which allow an ex-/import of a plugin's configuration: `sw:plugin:config:list` and `sw:plugin:config:set`. If you write a script you could easily import a configuration by calling the `sw:plugin:config:set` command a few times. 
If this doesn't meet your requirements I would recommend doing a pr instead of a new plugin.

Currently I'm thinking of a way to add shopping worlds and shop pages into a VCS.  But this is still just a concept ;)

**Comment by lhwparis** [comment]
thanks for the hint i wrote a little script. i ll try to refactor it and send it as a PR.
export and import of shopping worlds would be a nice feature :)
